### ISSUE TITLE
https_suffix.html problem

### ISSUE THREAD

**Issue by cheonmux** [pothi/wordpress-nginx#17]
Hello. I truly thank you for sharing useful information. 

I applied Wp-rocket.conf in your Github onto Nginx which I am using, 

but an error occurs that https_suffix.html file can't be found. 

I am using rocket, but I can't create the file. Could you tell me what I should do about this matter?

Thank you.

**Comment by cheonmux** [comment]
Hi, thanks for answering.

Yes, that file is correct one. I checked WP-ROCKET folder but I could not find the file. There were only several folders and index.html file. (Screenshot ->[](https://i.imgur.com/0eYDMt0.png) , [](https://i.imgur.com/vtPxiCr.png)

Also, I checked with Chrome develper tool that WP-ROCKET was working properly, and the right of cache folder is also set as 755 (www-data). 

Is it because there is a problem in my server or rocket setting? In addition, I applied [Rocket-nginx](https://github.com/maximejobin/rocket-nginx) as well.

Thank you.

**Comment by pothi** [comment]
Hi @cheonmux,

The line https://github.com/pothi/wordpress-nginx/blob/master/globals/wp-rocket.conf#L39 actually looks for index.html file (or index-https.html file in case of SSL enabled sites) and then if it is not found, it passes the query to PHP. That's why WP Rocket plugin works in your site.

https_suffix is actually a variable generated by https://github.com/pothi/wordpress-nginx/blob/master/conf.d/common.conf#L36 .

Your best friend is to turn on debugging in Nginx, so that you can understand how Nginx works behind the scene. it is each to catch configuration errors in this way.

**Comment by pothi** [comment]
Hi @cheonmux ,

I noticed that you started using the other config mentioned earlier. I hope it fits your current workflow. So, I will close this for now. Please feel free to re-open, if you use this config again and if you encounter the same issue.

Thanks.
