### ISSUE TITLE
force trailing slash to front end only.

### ISSUE THREAD

**Issue by KrashKartMedia** [pothi/wordpress-nginx#22]
Do you have a clever way of forcing trailing slashes to URLS on the front

/about-us/
/contact/our-team/

but leave the slash off

/wp-includes/js/file.js

We noticed that when you force trailing slashes, we could use the backend to update posts.

**Comment by pothi** [comment]
**Short answer**: Please contact me via https://www.tinywp.in/contact/ for any custom implementation or for any discussion on custom configuration. My hourly rate is USD25 per hour as of now.

**Long answer**: It is easy and it is recommended to set a trailing slash using WordPress permalinks. When we *force* trailing slash using a custom configuration, it may be lost when we switch the web server (Nginx) to another web server (such as [Caddy](https://caddyserver.com/)). It is possible to force trailing slash in Nginx, depending on the use-case. It may need some custom configuration on Nginx part. At times, we may need to use our own version of Nginx (compiled from source) in order to achieve the desired result.

I'd prefer to close this issue as a lot of sites have been working fine with trailing slash using this repo. This repo is *watched* my multiple people who may not be interested in discussion custom configurations here. Thanks.
