### ISSUE TITLE
$wpsc

### ISSUE THREAD

**Issue by negrusti** [pothi/wordpress-nginx#6]
Hello,
where does $wpsc variable comes from in wprocket.conf? That sounds like WordPress SuperCache?

**Comment by pothi** [comment]
Correct. The variable is actually "$wpsc_https" as can be seen at https://github.com/pothi/wordpress-nginx/blob/master/conf.d/common.conf#L33 . Originally, I created the variable for WPSC and since both use the same pattern for SSL powered sites, I used the same variable for WP Rocket too. Nevertheless, it should work as expected, as the variable is defined in conf.d/common.conf file. Thanks.

**Comment by pothi** [comment]
Hello,

The naming has been changed now as can be seen at https://github.com/pothi/wordpress-nginx/blob/master/conf.d/common.conf#L36 . So, I will close this for now. Please feel free to re-open, if you have any further questions on this.

Thanks.
